### ISSUE TITLE
一点疑惑

### ISSUE THREAD

**Issue by ultisigand** [lsr3406/Power-MVC#1]
您好，在函数setNewOpfParameters中计算Δy时，偏移量是否少了
```
self.opf.delta_x = self.opf.correction(end-self.opf.n_eq-self.opf.n_state+1:end-self.opf.n_eq);
self.opf.delta_y = self.opf.correction(4.*self.opf.n_ieq+1:4.*self.opf.n_ieq+self.opf.n_eq);

```
根据王锡凡《现代电力系统分析》书中，Δy是修正方程解中的最后一个
个人认为应当改为
```
self.opf.delta_y = self.opf.correction(end-self.opf.n_eq+1:end);

```
还是说这里有其他的设计，希望不吝赐教。

**Comment by lsr3406** [comment]
![Screen Shot 2021-05-12 at 23 07 09](https://user-images.githubusercontent.com/22501056/117998775-ca829380-b376-11eb-981b-09d4093d683b.png)

你说的有道理哎, 因为长度符合后面的计算公式也没报过错, 但实际上取到的 Δy, 是从 Δx 应有的位置取了等式约束数量的变量. 多谢 O(∩_∩)O~
